# Generated by Django 2.2.9 on 2020-05-22 09:09

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0003_remove_kv1line_is_ferry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kv1journey',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kv1journeystop',
            name='stoptype',
            field=models.CharField(choices=[('FIRST', 'Beginhalte'), ('INTERMEDIATE', 'Tussenhalte'), ('LAST', 'Eindhalte')], default='INTERMEDIATE', max_length=12),
        ),
        migrations.AlterField(
            model_name='kv1line',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kv1line',
            name='stop_map',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='kv1stop',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10),
        ),
    ]
