# Generated by Django 2.2.17 on 2021-01-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200522_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importDate', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='kv1journey',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kv1line',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kv1stop',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10),
        ),
    ]
