# Generated by Django 2.2.28 on 2023-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0005_auto_20210129_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importstatus',
            name='status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='kv1stop',
            name='name',
            field=models.CharField(max_length=102),
        ),
    ]
