# Generated by Django 2.2.9 on 2020-04-17 12:48

from django.db import migrations, models
import django.db.models.deletion
import openebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200416_1851'),
        ('openebs', '0007_auto_20160403_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17change',
            name='autorecover',
            field=models.BooleanField(default=False, verbose_name='Autorecover?'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='showcancelledtrip',
            field=models.BooleanField(default=True, verbose_name='Show_cancelled?'),
        )
    ]
