# Generated by Django 2.2.9 on 2020-04-16 16:51

from django.db import migrations, models
import django.db.models.deletion
import openebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200416_1851'),
        ('openebs', '0007_auto_20160403_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kv17ChangeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataownercode', models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder')),
                ('operatingday', models.DateField(verbose_name='Datum')),
                ('begintime', models.DateTimeField(blank=True, default=openebs.models.get_start_service, null=True, verbose_name='Ingangstijd')),
                ('endtime', models.DateTimeField(blank=True, default=openebs.models.get_end_service, null=True, verbose_name='Eindtijd')),
                ('autorecover', models.BooleanField(default=True, verbose_name='Autorecover?')),
                ('showcancelledtrip', models.BooleanField(default=True, verbose_name='Show_cancelled?')),
                ('is_cancel', models.BooleanField(default=True, help_text='Lijn kan ook een toelichting zijn voor een halte', verbose_name='Opgeheven?')),
                ('is_recovered', models.BooleanField(default=False, verbose_name='Teruggedraaid?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recovered', models.DateTimeField(blank=True, null=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line', verbose_name='Lijn')),
            ],
            options={
                'verbose_name': 'Lijnaanpassing',
                'verbose_name_plural': 'Lijnaanpassingen',
                'permissions': (('view_change_line', 'Lijnaanpassingen bekijken'), ('add_change_line', 'Lijnaanpassingen aanmaken')),
                'unique_together': {('operatingday', 'line', 'begintime')},
            },
        ),
        migrations.AlterField(
            model_name='kv15log',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenario',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='advicetype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Advies'), (255, 'Ongedefineerd')], null=True, verbose_name='Type advies'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='effecttype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Effect'), (255, 'Ongedefineerd')], null=True, verbose_name='Type gevolg'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='measuretype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemene Maatregel'), (255, 'Ongedefineerd')], null=True, verbose_name='Type aanpassing'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='messagedurationtype',
            field=models.CharField(choices=[('REMOVE', 'Verwijder'), ('FIRSTVEJO', 'Volgende rit'), ('ENDTIME', 'Eind Tijd')], default='ENDTIME', max_length=10, verbose_name='Type tijdsrooster'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='messagepriority',
            field=models.CharField(choices=[('CALAMITY', 'Calamiteit'), ('PTPROCESS', 'OV'), ('COMMERCIAL', 'Commercieel'), ('MISC', 'Overig')], default='PTPROCESS', max_length=10, verbose_name='Prioriteit'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='messagetype',
            field=models.CharField(choices=[('GENERAL', 'Algemeen'), ('ADDITIONAL', 'Extra'), ('OVERRULE', 'Overschrijf'), ('BOTTOMLINE', 'Onderaan')], default='GENERAL', max_length=10, verbose_name='Type bericht'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='reasontype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Overig'), (2, 'Personeel'), (3, 'Materieel'), (4, 'Omgeving'), (255, 'Ongedefinieerd')], null=True, verbose_name='Type oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='subadvicetype',
            field=models.CharField(blank=True, choices=[('0', 'geen'), ('1', 'niet reizen'), ('2', 'reizen met ander ov'), ('3_1', 'overstappen in'), ('3_2', 'reizen via'), ('3_3', 'in-/uitstappen')], max_length=10, verbose_name='Advies'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='subeffecttype',
            field=models.CharField(blank=True, choices=[('0', 'onbekend'), ('11', 'minder vervoer'), ('5', 'geen vervoer'), ('6', 'vervoer ontregeld'), ('5', 'geen treinen'), ('4', 'omleiding'), ('4_1', 'omleiding met vertraging'), ('3_1', 'vertraging onbekend'), ('3_2', 'vertraging 5 min.'), ('3_3', 'vertraging 10 min.'), ('3_4', 'vertraging 15 min.'), ('3_5', 'vertraging 30 min.'), ('3_6', 'vertraging 45 min.'), ('3_7', 'vertraging 60 min.'), ('3_8', 'vertraging 60 min. en meer'), ('3_9', 'vertraging 5 tot 10 min.'), ('3_10', 'vertraging 10 tot 15 min.'), ('3_11', 'vertraging 15 tot 30 min.'), ('3_12', 'vertraging 30 tot 60 min.'), ('5_1', 'vervallen halte(n)'), ('5_2', 'traject vervallen')], max_length=10, verbose_name='Gevolg'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='submeasuretype',
            field=models.CharField(blank=True, choices=[('0', 'extra vervoer'), ('1', 'vervallen halte(n)'), ('2', 'vervangende halte(n)'), ('3', 'rijden via omweg'), ('4_1', 'geen businzet'), ('4_2', 'beperkte businzet'), ('4_3', 'businzet'), ('5_1', 'geen treinen'), ('5_2', 'minder treinen'), ('5_3', 'treinen rijden via'), ('6', 'geen'), ('7', 'route aangepast')], max_length=10, verbose_name='Aanpassing'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='subreasontype',
            field=models.CharField(blank=True, choices=[('255', 'Onbekend'), ('0_1', 'Eerdere verstoring'), ('11', 'Herstel werkzaamheden'), ('11_2', 'Uitloop herstelwerkzaamheden'), ('12', 'Stroomstoring'), ('12_1', 'Defecte bovenleiding'), ('12_2', 'Uitloop werkzaamheden'), ('14', 'Defecte brug'), ('14', 'Wateroverlast'), ('14_1', 'Defect viaduct'), ('15', 'File'), ('16', 'Route versperd'), ('16', 'Stremming'), ('17', 'Mensen op de route'), ('18', 'Auto in spoor'), ('19_1', 'Omgevallen bomen'), ('20', 'Vee op de route'), ('23', 'Werkzaamheden'), ('23_1', 'Rioleringswerkzaamheden'), ('23_2', 'Wegwerkzaamheden'), ('23_3', 'Asfalteringswerkzaamheden'), ('23_4', 'Bestratingswerkzaamheden'), ('24_1', 'Optocht'), ('24_10', 'Kermis'), ('24_11', 'Koniginnedag'), ('24_12', 'Marathon'), ('24_13', 'Wielerronde'), ('24_14', 'Voetbalwedstrijd'), ('24_15', 'Herdenking'), ('24_16', 'Avondvierdaagse'), ('24_6', 'Bloemencorso'), ('24_7', 'Braderie'), ('24_8', 'Carnaval'), ('24_9', 'Jaarmarkt'), ('26_1', 'Snelheidsbeperkingen'), ('26_2', 'Logistieke problemen'), ('3', 'Sneeuw'), ('3_1', 'Op last van de politie'), ('3_11', 'Ontruiming'), ('3_15', 'Ruimen WO II bom'), ('3_17', 'Op last van de brandweer'), ('3_9', 'Bommelding'), ('4', 'Brand'), ('4', 'Seinstoring'), ('4', 'Tekort aan personeel'), ('4_1', 'Sein en wisselstoring'), ('5', 'Ontsporing'), ('5', 'Staking'), ('5', 'Storm'), ('5', 'Vakbondsacties'), ('5_1', 'Mogelijke staking'), ('6', 'Ongeval'), ('6', 'Stiptheidsactie'), ('6_2', 'Defecte trein'), ('6_3', 'Aanrijding met een persoon'), ('6_4', 'Passagier onwel'), ('6_6', 'Aanrijding'), ('7', 'Defect materieel'), ('7', 'Extreme drukte'), ('8_1', 'Defect spoor'), ('8_4', 'Tekort aan materieel'), ('8_10', 'Wisselstoring'), ('8_11', 'Overwegstoring'), ('8_12', 'Storing in verkeersleidingsysteem'), ('8_13', 'Gladde sporen'), ('9', 'Herstelwerkzaamheden'), ('9_1', 'Gladheid'), ('9_2', 'IJsgang'), ('9_2', 'IJzel'), ('255', 'Weersomstandigheden'), ('255_1', 'Blikeminslag')], max_length=10, verbose_name='Oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='advicetype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Advies'), (255, 'Ongedefineerd')], null=True, verbose_name='Type advies'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='effecttype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Effect'), (255, 'Ongedefineerd')], null=True, verbose_name='Type gevolg'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='measuretype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemene Maatregel'), (255, 'Ongedefineerd')], null=True, verbose_name='Type aanpassing'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='messagedurationtype',
            field=models.CharField(choices=[('REMOVE', 'Verwijder'), ('FIRSTVEJO', 'Volgende rit'), ('ENDTIME', 'Eind Tijd')], default='ENDTIME', max_length=10, verbose_name='Type tijdsrooster'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='messagepriority',
            field=models.CharField(choices=[('CALAMITY', 'Calamiteit'), ('PTPROCESS', 'OV'), ('COMMERCIAL', 'Commercieel'), ('MISC', 'Overig')], default='PTPROCESS', max_length=10, verbose_name='Prioriteit'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='messagetype',
            field=models.CharField(choices=[('GENERAL', 'Algemeen'), ('ADDITIONAL', 'Extra'), ('OVERRULE', 'Overschrijf'), ('BOTTOMLINE', 'Onderaan')], default='GENERAL', max_length=10, verbose_name='Type bericht'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='reasontype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Overig'), (2, 'Personeel'), (3, 'Materieel'), (4, 'Omgeving'), (255, 'Ongedefinieerd')], null=True, verbose_name='Type oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='subadvicetype',
            field=models.CharField(blank=True, choices=[('0', 'geen'), ('1', 'niet reizen'), ('2', 'reizen met ander ov'), ('3_1', 'overstappen in'), ('3_2', 'reizen via'), ('3_3', 'in-/uitstappen')], max_length=10, verbose_name='Advies'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='subeffecttype',
            field=models.CharField(blank=True, choices=[('0', 'onbekend'), ('11', 'minder vervoer'), ('5', 'geen vervoer'), ('6', 'vervoer ontregeld'), ('5', 'geen treinen'), ('4', 'omleiding'), ('4_1', 'omleiding met vertraging'), ('3_1', 'vertraging onbekend'), ('3_2', 'vertraging 5 min.'), ('3_3', 'vertraging 10 min.'), ('3_4', 'vertraging 15 min.'), ('3_5', 'vertraging 30 min.'), ('3_6', 'vertraging 45 min.'), ('3_7', 'vertraging 60 min.'), ('3_8', 'vertraging 60 min. en meer'), ('3_9', 'vertraging 5 tot 10 min.'), ('3_10', 'vertraging 10 tot 15 min.'), ('3_11', 'vertraging 15 tot 30 min.'), ('3_12', 'vertraging 30 tot 60 min.'), ('5_1', 'vervallen halte(n)'), ('5_2', 'traject vervallen')], max_length=10, verbose_name='Gevolg'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='submeasuretype',
            field=models.CharField(blank=True, choices=[('0', 'extra vervoer'), ('1', 'vervallen halte(n)'), ('2', 'vervangende halte(n)'), ('3', 'rijden via omweg'), ('4_1', 'geen businzet'), ('4_2', 'beperkte businzet'), ('4_3', 'businzet'), ('5_1', 'geen treinen'), ('5_2', 'minder treinen'), ('5_3', 'treinen rijden via'), ('6', 'geen'), ('7', 'route aangepast')], max_length=10, verbose_name='Aanpassing'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='subreasontype',
            field=models.CharField(blank=True, choices=[('255', 'Onbekend'), ('0_1', 'Eerdere verstoring'), ('11', 'Herstel werkzaamheden'), ('11_2', 'Uitloop herstelwerkzaamheden'), ('12', 'Stroomstoring'), ('12_1', 'Defecte bovenleiding'), ('12_2', 'Uitloop werkzaamheden'), ('14', 'Defecte brug'), ('14', 'Wateroverlast'), ('14_1', 'Defect viaduct'), ('15', 'File'), ('16', 'Route versperd'), ('16', 'Stremming'), ('17', 'Mensen op de route'), ('18', 'Auto in spoor'), ('19_1', 'Omgevallen bomen'), ('20', 'Vee op de route'), ('23', 'Werkzaamheden'), ('23_1', 'Rioleringswerkzaamheden'), ('23_2', 'Wegwerkzaamheden'), ('23_3', 'Asfalteringswerkzaamheden'), ('23_4', 'Bestratingswerkzaamheden'), ('24_1', 'Optocht'), ('24_10', 'Kermis'), ('24_11', 'Koniginnedag'), ('24_12', 'Marathon'), ('24_13', 'Wielerronde'), ('24_14', 'Voetbalwedstrijd'), ('24_15', 'Herdenking'), ('24_16', 'Avondvierdaagse'), ('24_6', 'Bloemencorso'), ('24_7', 'Braderie'), ('24_8', 'Carnaval'), ('24_9', 'Jaarmarkt'), ('26_1', 'Snelheidsbeperkingen'), ('26_2', 'Logistieke problemen'), ('3', 'Sneeuw'), ('3_1', 'Op last van de politie'), ('3_11', 'Ontruiming'), ('3_15', 'Ruimen WO II bom'), ('3_17', 'Op last van de brandweer'), ('3_9', 'Bommelding'), ('4', 'Brand'), ('4', 'Seinstoring'), ('4', 'Tekort aan personeel'), ('4_1', 'Sein en wisselstoring'), ('5', 'Ontsporing'), ('5', 'Staking'), ('5', 'Storm'), ('5', 'Vakbondsacties'), ('5_1', 'Mogelijke staking'), ('6', 'Ongeval'), ('6', 'Stiptheidsactie'), ('6_2', 'Defecte trein'), ('6_3', 'Aanrijding met een persoon'), ('6_4', 'Passagier onwel'), ('6_6', 'Aanrijding'), ('7', 'Defect materieel'), ('7', 'Extreme drukte'), ('8_1', 'Defect spoor'), ('8_4', 'Tekort aan materieel'), ('8_10', 'Wisselstoring'), ('8_11', 'Overwegstoring'), ('8_12', 'Storing in verkeersleidingsysteem'), ('8_13', 'Gladde sporen'), ('9', 'Herstelwerkzaamheden'), ('9_1', 'Gladheid'), ('9_2', 'IJsgang'), ('9_2', 'IJzel'), ('255', 'Weersomstandigheden'), ('255_1', 'Blikeminslag')], max_length=10, verbose_name='Oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv17journeychange',
            name='advicetype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Advies'), (255, 'Ongedefineerd')], null=True, verbose_name='Type advies'),
        ),
        migrations.AlterField(
            model_name='kv17journeychange',
            name='reasontype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Overig'), (2, 'Personeel'), (3, 'Materieel'), (4, 'Omgeving'), (255, 'Ongedefinieerd')], null=True, verbose_name='Type oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv17journeychange',
            name='subadvicetype',
            field=models.CharField(blank=True, choices=[('0', 'geen'), ('1', 'niet reizen'), ('2', 'reizen met ander ov'), ('3_1', 'overstappen in'), ('3_2', 'reizen via'), ('3_3', 'in-/uitstappen')], max_length=10, verbose_name='Advies'),
        ),
        migrations.AlterField(
            model_name='kv17journeychange',
            name='subreasontype',
            field=models.CharField(blank=True, choices=[('255', 'Onbekend'), ('0_1', 'Eerdere verstoring'), ('11', 'Herstel werkzaamheden'), ('11_2', 'Uitloop herstelwerkzaamheden'), ('12', 'Stroomstoring'), ('12_1', 'Defecte bovenleiding'), ('12_2', 'Uitloop werkzaamheden'), ('14', 'Defecte brug'), ('14', 'Wateroverlast'), ('14_1', 'Defect viaduct'), ('15', 'File'), ('16', 'Route versperd'), ('16', 'Stremming'), ('17', 'Mensen op de route'), ('18', 'Auto in spoor'), ('19_1', 'Omgevallen bomen'), ('20', 'Vee op de route'), ('23', 'Werkzaamheden'), ('23_1', 'Rioleringswerkzaamheden'), ('23_2', 'Wegwerkzaamheden'), ('23_3', 'Asfalteringswerkzaamheden'), ('23_4', 'Bestratingswerkzaamheden'), ('24_1', 'Optocht'), ('24_10', 'Kermis'), ('24_11', 'Koniginnedag'), ('24_12', 'Marathon'), ('24_13', 'Wielerronde'), ('24_14', 'Voetbalwedstrijd'), ('24_15', 'Herdenking'), ('24_16', 'Avondvierdaagse'), ('24_6', 'Bloemencorso'), ('24_7', 'Braderie'), ('24_8', 'Carnaval'), ('24_9', 'Jaarmarkt'), ('26_1', 'Snelheidsbeperkingen'), ('26_2', 'Logistieke problemen'), ('3', 'Sneeuw'), ('3_1', 'Op last van de politie'), ('3_11', 'Ontruiming'), ('3_15', 'Ruimen WO II bom'), ('3_17', 'Op last van de brandweer'), ('3_9', 'Bommelding'), ('4', 'Brand'), ('4', 'Seinstoring'), ('4', 'Tekort aan personeel'), ('4_1', 'Sein en wisselstoring'), ('5', 'Ontsporing'), ('5', 'Staking'), ('5', 'Storm'), ('5', 'Vakbondsacties'), ('5_1', 'Mogelijke staking'), ('6', 'Ongeval'), ('6', 'Stiptheidsactie'), ('6_2', 'Defecte trein'), ('6_3', 'Aanrijding met een persoon'), ('6_4', 'Passagier onwel'), ('6_6', 'Aanrijding'), ('7', 'Defect materieel'), ('7', 'Extreme drukte'), ('8_1', 'Defect spoor'), ('8_4', 'Tekort aan materieel'), ('8_10', 'Wisselstoring'), ('8_11', 'Overwegstoring'), ('8_12', 'Storing in verkeersleidingsysteem'), ('8_13', 'Gladde sporen'), ('9', 'Herstelwerkzaamheden'), ('9_1', 'Gladheid'), ('9_2', 'IJsgang'), ('9_2', 'IJzel'), ('255', 'Weersomstandigheden'), ('255_1', 'Blikeminslag')], max_length=10, verbose_name='Oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv17stopchange',
            name='advicetype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Advies'), (255, 'Ongedefineerd')], null=True, verbose_name='Type advies'),
        ),
        migrations.AlterField(
            model_name='kv17stopchange',
            name='reasontype',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Overig'), (2, 'Personeel'), (3, 'Materieel'), (4, 'Omgeving'), (255, 'Ongedefinieerd')], null=True, verbose_name='Type oorzaak'),
        ),
        migrations.AlterField(
            model_name='kv17stopchange',
            name='stoptype',
            field=models.CharField(blank=True, choices=[('FIRST', 'Beginhalte'), ('INTERMEDIATE', 'Tussenhalte'), ('LAST', 'Eindhalte')], default='INTERMEDIATE', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='kv17stopchange',
            name='subadvicetype',
            field=models.CharField(blank=True, choices=[('0', 'geen'), ('1', 'niet reizen'), ('2', 'reizen met ander ov'), ('3_1', 'overstappen in'), ('3_2', 'reizen via'), ('3_3', 'in-/uitstappen')], max_length=10, verbose_name='Advies'),
        ),
        migrations.AlterField(
            model_name='kv17stopchange',
            name='subreasontype',
            field=models.CharField(blank=True, choices=[('255', 'Onbekend'), ('0_1', 'Eerdere verstoring'), ('11', 'Herstel werkzaamheden'), ('11_2', 'Uitloop herstelwerkzaamheden'), ('12', 'Stroomstoring'), ('12_1', 'Defecte bovenleiding'), ('12_2', 'Uitloop werkzaamheden'), ('14', 'Defecte brug'), ('14', 'Wateroverlast'), ('14_1', 'Defect viaduct'), ('15', 'File'), ('16', 'Route versperd'), ('16', 'Stremming'), ('17', 'Mensen op de route'), ('18', 'Auto in spoor'), ('19_1', 'Omgevallen bomen'), ('20', 'Vee op de route'), ('23', 'Werkzaamheden'), ('23_1', 'Rioleringswerkzaamheden'), ('23_2', 'Wegwerkzaamheden'), ('23_3', 'Asfalteringswerkzaamheden'), ('23_4', 'Bestratingswerkzaamheden'), ('24_1', 'Optocht'), ('24_10', 'Kermis'), ('24_11', 'Koniginnedag'), ('24_12', 'Marathon'), ('24_13', 'Wielerronde'), ('24_14', 'Voetbalwedstrijd'), ('24_15', 'Herdenking'), ('24_16', 'Avondvierdaagse'), ('24_6', 'Bloemencorso'), ('24_7', 'Braderie'), ('24_8', 'Carnaval'), ('24_9', 'Jaarmarkt'), ('26_1', 'Snelheidsbeperkingen'), ('26_2', 'Logistieke problemen'), ('3', 'Sneeuw'), ('3_1', 'Op last van de politie'), ('3_11', 'Ontruiming'), ('3_15', 'Ruimen WO II bom'), ('3_17', 'Op last van de brandweer'), ('3_9', 'Bommelding'), ('4', 'Brand'), ('4', 'Seinstoring'), ('4', 'Tekort aan personeel'), ('4_1', 'Sein en wisselstoring'), ('5', 'Ontsporing'), ('5', 'Staking'), ('5', 'Storm'), ('5', 'Vakbondsacties'), ('5_1', 'Mogelijke staking'), ('6', 'Ongeval'), ('6', 'Stiptheidsactie'), ('6_2', 'Defecte trein'), ('6_3', 'Aanrijding met een persoon'), ('6_4', 'Passagier onwel'), ('6_6', 'Aanrijding'), ('7', 'Defect materieel'), ('7', 'Extreme drukte'), ('8_1', 'Defect spoor'), ('8_4', 'Tekort aan materieel'), ('8_10', 'Wisselstoring'), ('8_11', 'Overwegstoring'), ('8_12', 'Storing in verkeersleidingsysteem'), ('8_13', 'Gladde sporen'), ('9', 'Herstelwerkzaamheden'), ('9_1', 'Gladheid'), ('9_2', 'IJsgang'), ('9_2', 'IJzel'), ('255', 'Weersomstandigheden'), ('255_1', 'Blikeminslag')], max_length=10, verbose_name='Oorzaak'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.CreateModel(
            name='Kv17ChangeLineChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasontype', models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Overig'), (2, 'Personeel'), (3, 'Materieel'), (4, 'Omgeving'), (255, 'Ongedefinieerd')], null=True, verbose_name='Type oorzaak')),
                ('subreasontype', models.CharField(blank=True, choices=[('255', 'Onbekend'), ('0_1', 'Eerdere verstoring'), ('11', 'Herstel werkzaamheden'), ('11_2', 'Uitloop herstelwerkzaamheden'), ('12', 'Stroomstoring'), ('12_1', 'Defecte bovenleiding'), ('12_2', 'Uitloop werkzaamheden'), ('14', 'Defecte brug'), ('14', 'Wateroverlast'), ('14_1', 'Defect viaduct'), ('15', 'File'), ('16', 'Route versperd'), ('16', 'Stremming'), ('17', 'Mensen op de route'), ('18', 'Auto in spoor'), ('19_1', 'Omgevallen bomen'), ('20', 'Vee op de route'), ('23', 'Werkzaamheden'), ('23_1', 'Rioleringswerkzaamheden'), ('23_2', 'Wegwerkzaamheden'), ('23_3', 'Asfalteringswerkzaamheden'), ('23_4', 'Bestratingswerkzaamheden'), ('24_1', 'Optocht'), ('24_10', 'Kermis'), ('24_11', 'Koniginnedag'), ('24_12', 'Marathon'), ('24_13', 'Wielerronde'), ('24_14', 'Voetbalwedstrijd'), ('24_15', 'Herdenking'), ('24_16', 'Avondvierdaagse'), ('24_6', 'Bloemencorso'), ('24_7', 'Braderie'), ('24_8', 'Carnaval'), ('24_9', 'Jaarmarkt'), ('26_1', 'Snelheidsbeperkingen'), ('26_2', 'Logistieke problemen'), ('3', 'Sneeuw'), ('3_1', 'Op last van de politie'), ('3_11', 'Ontruiming'), ('3_15', 'Ruimen WO II bom'), ('3_17', 'Op last van de brandweer'), ('3_9', 'Bommelding'), ('4', 'Brand'), ('4', 'Seinstoring'), ('4', 'Tekort aan personeel'), ('4_1', 'Sein en wisselstoring'), ('5', 'Ontsporing'), ('5', 'Staking'), ('5', 'Storm'), ('5', 'Vakbondsacties'), ('5_1', 'Mogelijke staking'), ('6', 'Ongeval'), ('6', 'Stiptheidsactie'), ('6_2', 'Defecte trein'), ('6_3', 'Aanrijding met een persoon'), ('6_4', 'Passagier onwel'), ('6_6', 'Aanrijding'), ('7', 'Defect materieel'), ('7', 'Extreme drukte'), ('8_1', 'Defect spoor'), ('8_4', 'Tekort aan materieel'), ('8_10', 'Wisselstoring'), ('8_11', 'Overwegstoring'), ('8_12', 'Storing in verkeersleidingsysteem'), ('8_13', 'Gladde sporen'), ('9', 'Herstelwerkzaamheden'), ('9_1', 'Gladheid'), ('9_2', 'IJsgang'), ('9_2', 'IJzel'), ('255', 'Weersomstandigheden'), ('255_1', 'Blikeminslag')], max_length=10, verbose_name='Oorzaak')),
                ('reasoncontent', models.CharField(blank=True, max_length=255, verbose_name='Uitleg oorzaak')),
                ('advicetype', models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Advies'), (255, 'Ongedefineerd')], null=True, verbose_name='Type advies')),
                ('subadvicetype', models.CharField(blank=True, choices=[('0', 'geen'), ('1', 'niet reizen'), ('2', 'reizen met ander ov'), ('3_1', 'overstappen in'), ('3_2', 'reizen via'), ('3_3', 'in-/uitstappen')], max_length=10, verbose_name='Advies')),
                ('advicecontent', models.CharField(blank=True, max_length=255, verbose_name='Uitleg advies')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='openebs.Kv17ChangeLine')),
            ],
            options={
                'verbose_name': 'Lijnaanpassingsdetails',
                'verbose_name_plural': 'Lijnaanpassingendetails',
            },
        ),
    ]
