# Generated by Django 2.2.9 on 2020-05-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0008_auto_20200508_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17change',
            name='is_alljourneysofline',
            field=models.BooleanField(default=False, verbose_name='Alle ritten'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='is_alllines',
            field=models.BooleanField(default=False, verbose_name='Alle ritten'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='kv1.Kv1Journey', verbose_name='Rit'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line', verbose_name='Lijn'),
        ),
    ]
