# Generated by Django 2.2.9 on 2020-04-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0008_auto_20200416_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17changeline',
            name='monitoring_error',
            field=models.CharField(choices=[('GPS', 'Storing in de GPS van het voertuig'), ('GPRS', 'Storing in het mobiele netwerk'), ('Radio', 'Storing in de radioverbinding'), ('General', 'Voertuigsysteem werkt niet'), ('NoSystem', 'Voertuig heeft geen volgapparatuur'), ('other', 'Andere oorzaak'), ('unknown', 'Onbekende oorzaak')], default=False, max_length=40, verbose_name='Monitoring_error'),
        ),
    ]
