# Generated by Django 2.2.9 on 2020-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0008_auto_20200522_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17change',
            name='autorecover',
            field=models.BooleanField(default=False, verbose_name='Automatisch herstellen'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='showcancelledtrip',
            field=models.BooleanField(default=True, verbose_name='Toon opgeheven rit'),
        ),
    ]
