# Generated by Django 2.2.9 on 2020-10-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200522_1109'),
        ('openebs', '0008_auto_20200522_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kv15ScenarioLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='openebs.Kv15ScenarioMessage')),
            ],
        ),
    ]
