# Generated by Django 2.2.17 on 2021-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0008_auto_20200522_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kv15log',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenario',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry')], max_length=10, verbose_name='Vervoerder'),
        ),
    ]
