# Generated by Django 2.2.9 on 2020-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200508_1336'),
        ('openebs', '0009_auto_20200508_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kv17change',
            unique_together={('operatingday', 'line', 'journey', 'reinforcement', 'is_alljourneysofline', 'is_alllines')},
        ),
    ]
