# Generated by Django 2.2.17 on 2021-02-01 12:38

from django.db import migrations, models
import django.db.models.deletion
import openebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0005_auto_20210129_1622'),
        ('openebs', '0009_auto_20210129_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kv17change',
            options={'permissions': (('view_change', 'Ritaanpassingen bekijken'), ('add_change', 'Ritaanpassingen aanmaken'), ('cancel_lines', 'Lijnen annuleren'), ('cancel_alllines', 'Vervoerder annuleren')), 'verbose_name': 'Ritaanpassing', 'verbose_name_plural': 'Ritaanpassingen'},
        ),
        migrations.AddField(
            model_name='kv17change',
            name='begintime',
            field=models.DateTimeField(blank=True, default=openebs.models.get_start_service, null=True, verbose_name='Ingangstijd'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='endtime',
            field=models.DateTimeField(blank=True, default=openebs.models.get_end_service, null=True, verbose_name='Eindtijd'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='is_alljourneysofline',
            field=models.BooleanField(default=False, verbose_name='Alle ritten'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='is_alllines',
            field=models.BooleanField(default=False, verbose_name='Alle lijnen'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='journey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='kv1.Kv1Journey', verbose_name='Rit'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line', verbose_name='Lijn'),
        ),
        migrations.AlterUniqueTogether(
            name='kv17change',
            unique_together={('dataownercode', 'operatingday', 'line', 'journey', 'reinforcement', 'is_alljourneysofline', 'is_alllines', 'is_recovered', 'begintime')},
        ),
    ]
