# Generated by Django 2.2.9 on 2020-05-13 11:01

from django.db import migrations, models
import openebs.models


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200508_1336'),
        ('openebs', '0010_auto_20200508_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17change',
            name='begintime',
            field=models.DateTimeField(blank=True, default=openebs.models.get_start_service, null=True, verbose_name='Ingangstijd'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='endtime',
            field=models.DateTimeField(blank=True, default=openebs.models.get_end_service, null=True, verbose_name='Eindtijd'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='is_alllines',
            field=models.BooleanField(default=False, verbose_name='Alle lijnen'),
        ),
        migrations.AlterUniqueTogether(
            name='kv17change',
            unique_together={('operatingday', 'line', 'journey', 'reinforcement', 'is_alljourneysofline', 'is_alllines', 'begintime')},
        ),
    ]
