# Generated by Django 2.2.28 on 2023-04-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0006_auto_20230406_1454'),
        ('openebs', '0010_auto_20210201_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kv15scenariostop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_stop', to='kv1.Kv1Stop'),
        ),
        migrations.CreateModel(
            name='Kv15ScenarioLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kv1.Kv1Line')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='openebs.Kv15ScenarioMessage')),
            ],
        ),
    ]
