# Generated by Django 2.2.28 on 2023-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0011_auto_20230406_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv17change',
            name='autorecover',
            field=models.BooleanField(default=False, verbose_name='Automatisch herstellen'),
        ),
        migrations.AddField(
            model_name='kv17change',
            name='showcancelledtrip',
            field=models.BooleanField(default=True, verbose_name='Toon opgeheven rit'),
        ),
    ]
