# Generated by Django 2.2.9 on 2020-05-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200508_1336'),
        ('openebs', '0011_auto_20200513_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kv17change',
            unique_together={('dataownercode', 'operatingday', 'line', 'journey', 'reinforcement', 'is_alljourneysofline', 'is_alllines', 'is_recovered', 'begintime')},
        ),
    ]
