# Generated by Django 2.2.9 on 2020-06-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kv1', '0004_auto_20200522_1109'),
        ('openebs', '0011_kv17change_monitoring_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kv17Shorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passagesequencenumber', models.IntegerField(default=0, verbose_name='Passagenummer')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shorten_details', to='openebs.Kv17Change')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_shorten', to='kv1.Kv1Stop')),
            ],
            options={
                'verbose_name': 'Ritverkorting',
                'verbose_name_plural': 'Ritverkortingen',
                'permissions': (('view_shorten', 'Ritverkortingen bekijken'), ('add_shorten', 'Ritverkortingen aanmaken')),
            },
        ),
        migrations.CreateModel(
            name='Kv17MutationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passagesequencenumber', models.IntegerField(default=0, verbose_name='Passagenummer')),
                ('reasontype', models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Overig'), (2, 'Personeel'), (3, 'Materieel'), (4, 'Omgeving'), (255, 'Ongedefinieerd')], null=True, verbose_name='Type oorzaak')),
                ('subreasontype', models.CharField(blank=True, choices=[('255', 'Onbekend'), ('0_1', 'Eerdere verstoring'), ('11', 'Herstel werkzaamheden'), ('11_2', 'Uitloop herstelwerkzaamheden'), ('12', 'Stroomstoring'), ('12_1', 'Defecte bovenleiding'), ('12_2', 'Uitloop werkzaamheden'), ('14', 'Defecte brug'), ('14', 'Wateroverlast'), ('14_1', 'Defect viaduct'), ('15', 'File'), ('16', 'Route versperd'), ('16', 'Stremming'), ('17', 'Mensen op de route'), ('18', 'Auto in spoor'), ('19_1', 'Omgevallen bomen'), ('20', 'Vee op de route'), ('23', 'Werkzaamheden'), ('23_1', 'Rioleringswerkzaamheden'), ('23_2', 'Wegwerkzaamheden'), ('23_3', 'Asfalteringswerkzaamheden'), ('23_4', 'Bestratingswerkzaamheden'), ('24_1', 'Optocht'), ('24_10', 'Kermis'), ('24_11', 'Koniginnedag'), ('24_12', 'Marathon'), ('24_13', 'Wielerronde'), ('24_14', 'Voetbalwedstrijd'), ('24_15', 'Herdenking'), ('24_16', 'Avondvierdaagse'), ('24_6', 'Bloemencorso'), ('24_7', 'Braderie'), ('24_8', 'Carnaval'), ('24_9', 'Jaarmarkt'), ('26_1', 'Snelheidsbeperkingen'), ('26_2', 'Logistieke problemen'), ('3', 'Sneeuw'), ('3_1', 'Op last van de politie'), ('3_11', 'Ontruiming'), ('3_15', 'Ruimen WO II bom'), ('3_17', 'Op last van de brandweer'), ('3_9', 'Bommelding'), ('4', 'Brand'), ('4', 'Seinstoring'), ('4', 'Tekort aan personeel'), ('4_1', 'Sein en wisselstoring'), ('5', 'Ontsporing'), ('5', 'Staking'), ('5', 'Storm'), ('5', 'Vakbondsacties'), ('5_1', 'Mogelijke staking'), ('6', 'Ongeval'), ('6', 'Stiptheidsactie'), ('6_2', 'Defecte trein'), ('6_3', 'Aanrijding met een persoon'), ('6_4', 'Passagier onwel'), ('6_6', 'Aanrijding'), ('7', 'Defect materieel'), ('7', 'Extreme drukte'), ('8_1', 'Defect spoor'), ('8_4', 'Tekort aan materieel'), ('8_10', 'Wisselstoring'), ('8_11', 'Overwegstoring'), ('8_12', 'Storing in verkeersleidingsysteem'), ('8_13', 'Gladde sporen'), ('9', 'Herstelwerkzaamheden'), ('9_1', 'Gladheid'), ('9_2', 'IJsgang'), ('9_2', 'IJzel'), ('255', 'Weersomstandigheden'), ('255_1', 'Blikeminslag')], max_length=10, verbose_name='Oorzaak')),
                ('reasoncontent', models.CharField(blank=True, max_length=255, verbose_name='Uitleg oorzaak')),
                ('advicetype', models.SmallIntegerField(blank=True, choices=[(0, 'Onbekend'), (1, 'Algemeen Advies'), (255, 'Ongedefineerd')], null=True, verbose_name='Type advies')),
                ('subadvicetype', models.CharField(blank=True, choices=[('0', 'geen'), ('1', 'niet reizen'), ('2', 'reizen met ander ov'), ('3_1', 'overstappen in'), ('3_2', 'reizen via'), ('3_3', 'in-/uitstappen')], max_length=10, verbose_name='Advies')),
                ('advicecontent', models.CharField(blank=True, max_length=255, verbose_name='Uitleg advies')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_details_mutation_message', to='openebs.Kv17Change')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_mutation_message', to='kv1.Kv1Stop')),
            ],
            options={
                'verbose_name': 'Ritverkortingsdetails',
                'verbose_name_plural': 'Ritverkortingsdetails',
            },
        ),
    ]
