# Generated by Django 2.2.9 on 2020-05-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0012_auto_20200514_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kv17change',
            options={'permissions': (('view_change', 'Ritaanpassingen bekijken'), ('add_change', 'Ritaanpassingen aanmaken'), ('cancel_alllines', 'Vervoerder annuleren')), 'verbose_name': 'Ritaanpassing', 'verbose_name_plural': 'Ritaanpassingen'},
        ),
    ]
