# Generated by Django 2.2.9 on 2020-05-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0013_auto_20200518_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kv17change',
            options={'permissions': (('view_change', 'Ritaanpassingen bekijken'), ('add_change', 'Ritaanpassingen aanmaken'), ('cancel_alllines', 'Vervoerder annuleren'), ('cancel_lines', 'Lijnen annuleren')), 'verbose_name': 'Ritaanpassing', 'verbose_name_plural': 'Ritaanpassingen'},
        ),
    ]
