# Generated by Django 4.2.11 on 2024-08-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0015_alter_kv15log_dataownercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kv15log',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry'), ('ZTM', 'Gemeente Zoetermeer'), ('TESO', 'TESO'), ('DOEKSEN', 'Rederij Doeksen'), ('WPD', 'Wagenborg Passagiersdiensten')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenario',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry'), ('ZTM', 'Gemeente Zoetermeer'), ('TESO', 'TESO'), ('DOEKSEN', 'Rederij Doeksen'), ('WPD', 'Wagenborg Passagiersdiensten')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15scenariomessage',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry'), ('ZTM', 'Gemeente Zoetermeer'), ('TESO', 'TESO'), ('DOEKSEN', 'Rederij Doeksen'), ('WPD', 'Wagenborg Passagiersdiensten')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv15stopmessage',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry'), ('ZTM', 'Gemeente Zoetermeer'), ('TESO', 'TESO'), ('DOEKSEN', 'Rederij Doeksen'), ('WPD', 'Wagenborg Passagiersdiensten')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='kv17change',
            name='dataownercode',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry'), ('ZTM', 'Gemeente Zoetermeer'), ('TESO', 'TESO'), ('DOEKSEN', 'Rederij Doeksen'), ('WPD', 'Wagenborg Passagiersdiensten')], max_length=10, verbose_name='Vervoerder'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(choices=[('ARR', 'Arriva'), ('VTN', 'Veolia'), ('CXX', 'Connexxion'), ('EBS', 'EBS'), ('GVB', 'GVB'), ('HTM', 'HTM'), ('NS', 'Nederlandse Spoorwegen'), ('RET', 'RET'), ('SYNTUS', 'Syntus'), ('KEOLIS', 'Keolis'), ('QBUZZ', 'Qbuzz'), ('TCR', 'Taxi Centrale Renesse'), ('GOVI', 'GOVI'), ('WSF', 'Westerschelde Ferry'), ('ZTM', 'Gemeente Zoetermeer'), ('TESO', 'TESO'), ('DOEKSEN', 'Rederij Doeksen'), ('WPD', 'Wagenborg Passagiersdiensten')], max_length=10, verbose_name='Vervoerder'),
        ),
    ]
