# Generated by Django 4.2.15 on 2025-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openebs', '0016_alter_kv15log_dataownercode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kv15stopmessage',
            name='kv8messagecodedate',
            field=models.DateField(blank=True, null=True, verbose_name='KV8 Datum'),
        ),
        migrations.AddField(
            model_name='kv15stopmessage',
            name='kv8messagecodenumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='KV8 Volgnummer'),
        ),
    ]
